name: Docker Image CI

on:
  schedule:
    - cron: "00 12 * * *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcversion:
          - "1.8"
          - "1.8.3"
          - "1.8.4"
          - "1.8.5"
          - "1.8.6"
          - "1.8.7"
          - "1.8.9"
          - "1.9"
          - "1.9.2"
          - "1.9.4"
          - "1.10"
          - "1.10.2"
          - "1.11"
          - "1.11.1"
          - "1.11.2"
          - "1.12"
          - "1.12.1"
          - "1.12.2"
          - "1.13"
          - "1.13.1"
          - "1.13.2"
          - "1.14"
          - "1.14.1"
          - "1.14.2"
          - "1.14.4"
          - "1.15"
          - "1.15.1"
          - "1.15.2"
          - "1.16"
          - "1.16.1"
          - "1.16.2"
          - "1.16.3"
          - "1.16.4"
          - "1.16.5"
          - "1.17"

    steps:
    - uses: actions/checkout@v2
    - name: Build and push a spigot image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        MC_VERSION: ${{ matrix.mcversion }}
      run: |
        docker login -u tux2603 -p $DOCKER_TOKEN
        docker build . --file Dockerfile --tag tux2603/spigot:$MC_VERSION --build-arg MC_VERSION=$MC_VERSION
        docker image push tux2603/spigot:$MC_VERSION

