name: Docker Image CI

on:
  schedule:
    - cron: "00 12 * * *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - "1.8 8"
          - "1.8.3 8"
          - "1.8.8 8"
          - "1.9 8"
          - "1.9.2 8"
          - "1.9.4 8"
          - "1.10.2 8"
          - "1.11 8"
          - "1.11.1 8"
          - "1.11.2 8"
          - "1.12 8"
          - "1.12.1 8"
          - "1.12.2 8"
          - "1.13 11"
          - "1.13.1 11"
          - "1.13.2 11"
          - "1.14 11"
          - "1.14.1 11"
          - "1.14.2 11"
          - "1.14.3 11"
          - "1.14.4 11"
          - "1.15 11"
          - "1.15.1 11"
          - "1.15.2 11"
          - "1.16.1 11"
          - "1.16.2 11"
          - "1.16.3 11"
          - "1.16.4 11"
          - "1.16.5 11"
          - "1.17 16"
          - "1.17.1 16"
          - "latest 16"
        platform:
          - "linux/amd64"
          - "linux/arm/v7"
          - "linux/arm64/v8"
          - "linux/ppc64le"
          - "linux/s390x"


    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1 

    - name: Build and push a spigot image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        VERSIONS: ${{ matrix.versions }}
        PLATFORM: ${{ matrix.platform }}
      run: |
        docker login -u tux2603 -p $DOCKER_TOKEN
        MC_VERSION=`echo $VERSIONS | awk '{print $1}'`
        JAVA_VERSION=`echo $VERSIONS | awk '{print $2}'`
        echo "Building $MC_VERSION with $JAVA_VERSION"
        docker buildx build . --file Dockerfile --platform $PLATFORM --tag tux2603/spigot:$MC_VERSION --build-arg MC_VERSION=$MC_VERSION --build-arg JAVA_VERSION=$JAVA_VERSION
        docker image push tux2603/spigot:$MC_VERSION


